"""add image column to emote

Revision ID: 79f99cd56b4a
Revises: 2756b91abf70
Create Date: 2023-08-07 16:03:54.160127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f99cd56b4a'
down_revision = '2756b91abf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emote_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['emote_id'], ['emote.emote_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('emote', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emote', 'image')
    op.drop_table('favorites')
    # ### end Alembic commands ###
